apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::361768205211:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::361768205211:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EH1PAOOWAAPT
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-23T12:22:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "20313"
  uid: ab2577a9-6c38-4ac1-8016-b1e9a466d941
